# Generated by Django 4.0.1 on 2022-01-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Personnel Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnels',
                'db_table': 'db_personnel',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Role Name')),
                ('employees', models.ManyToManyField(blank=True, related_name='personnel_employee', to='personel.Personnel', verbose_name='Employees')),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_supervisor', to='personel.personnel', verbose_name='SuperVising Personnel')),
            ],
            options={
                'verbose_name': 'RoleAssignment',
                'verbose_name_plural': 'RoleAssignments',
                'db_table': 'role_assignment',
                'ordering': ['-id'],
            },
        ),
    ]
